version: "3.9"

services:
  db:
    image: postgres:14
    container_name: crehana_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: crehana_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["/app/entrypoint.sh"]

volumes:
  postgres_data: