version: '3.8'

services:
  test_db:
    image: postgres:15
    container_name: creahana_test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test_user"]
      interval: 3s
      retries: 5

volumes:
  test_db_data: